import { Member, Publication, ResearchArea, LifeEvent, NewsItem } from './types';

export const TEAM_MEMBERS: Member[] = [
  {
    id: '1',
    name: '武瑞东 (研究员)',
    nameEn: 'Ruidong Wu (Professor)',
    role: 'Faculty',
    cohort: '指导教师',
    cohortEn: 'Supervisor',
    image: 'https://picsum.photos/seed/faculty1/400/400',
    description: '主要研究方向为全球变化下的生物多样性保护与生物地理学。',
    descriptionEn: 'Research focuses on biodiversity conservation and biogeography under global change.',
    fullBio: '武瑞东，博士，研究员，博士生导师。主要从事保护生物地理学方向的科研与教学工作，系统开展了关键生态保护对象空间分布格局与形成机制、生态保护成效评估和保护优先区网络系统规划等方面的研究。先后主持国家自然科学基金项目（4项）、国家重点研发计划项目/专题、云南省基础研究专项重大项目/课题等科研项目。系统性研究成果，发表于Nature Communications, Global Change Biology,Frontiers in Ecology & the Environment,Communications Earth & Environment, Conservation Letters，Conservation Biology，Biological Conservation等国际权威期刊。研究成果为《中国生物多样性保护战略与行动计划（2011-2030）》、云南省"以国家公园为主体的自然保护地体系建设"、云南省生态产品价值核算、《四川省生物多样性保护战略与行动计划》、阿拉善"一亿棵梭梭"造林项目区规划等实践工作提供了科学支撑。',
    fullBioEn: 'Prof. Ruidong Wu is a researcher and doctoral supervisor at the Institute of International Rivers and Eco-Security, Yunnan University. His research focuses on conservation biogeography, systematically addressing the spatial distribution patterns and formation mechanisms of key conservation targets, evaluating ecological conservation effectiveness, and planning conservation priority area networks. He has led multiple research projects funded by the National Natural Science Foundation of China, the National Key R&D Program, and the Yunnan Provincial Basic Research Program. His research has been published in leading international journals including Nature Communications, Global Change Biology, Frontiers in Ecology & the Environment, Communications Earth & Environment, Conservation Letters, Conservation Biology, and Biological Conservation. His work has provided scientific support for China\'s Biodiversity Conservation Strategy and Action Plan, Yunnan\'s protected area system planning, and other conservation initiatives.',
    education: [
      '博士, 生态学, 某某大学, 2005',
      '硕士, 植物学, 某某大学, 2002',
      '学士, 测绘工程, 某某大学, 1999'
    ],
    educationEn: [
      'PhD, Ecology, 2005',
      'MS, Botany, 2002',
      'BS, Surveying Engineering, 1999'
    ],
    researchInterests: ['全球变化生物学', '空间生态学', '保护规划'],
    researchInterestsEn: ['Global Change Biology', 'Spatial Ecology', 'Conservation Planning'],
    email: 'rdwu@ynu.edu.cn',
  },
  {
    id: '2',
    name: '刘鑫 (Dr. Liu)',
    nameEn: 'Dr. Xin Liu',
    role: 'Postdoc',
    cohort: '博士后',
    cohortEn: 'Postdoc',
    image: 'https://picsum.photos/seed/postdoc1/400/400',
    description: '专注于高山植物的分布格局及其对气候变化的响应。',
    descriptionEn: 'Focuses on alpine plant distribution patterns and their responses to climate change.',
    fullBio: '刘鑫博士于2023年加入研究组。他的研究重点是全球维管植物的分布和全球生物多样性热点区域。',
    fullBioEn: 'Dr. Xin Liu joined the group in 2023. His research focuses on the global distribution of vascular plants and global biodiversity hotspots.',
    education: [
      '博士，生态学, 云南大学, 2026',
      '硕士, 资源与环境, 云南大学, 2023',
      '学士, 水资源工程, 西安理工大学, 2018'
    ],
    educationEn: [
      'PhD, Ecology, Yunnan University, 2026',
      'MS, Resources and Environment, Yunnan University, 2023',
      'BS, Water Resources Engineering, Xi\'an University of Technology, 2018'
    ],
    researchInterests: ['全球变化生物学', '物种分布建模'],
    researchInterestsEn: ['Global Change Biology', 'Species Distribution Modeling'],
  },
  {
    id: '3',
    name: '罗金怡',
    nameEn: 'Jinyi Luo',
    role: 'PhD Student',
    cohort: '2022级博士',
    cohortEn: '2022 PhD',
    image: 'https://picsum.photos/seed/student1/400/400',
    description: '研究岛屿生物地理学中的物种演化。',
    descriptionEn: 'Studies species evolution in island biogeography.',
    fullBio: '罗金怡同学目前正在攻读博士学位，主要研究全球生物多样性与环境异质性之间的响应关系。',
    fullBioEn: 'Jinyi Luo is currently pursuing her PhD, primarily studying the relationship between global biodiversity and environmental heterogeneity.',
    education: ['学士, 生物科学, 某某大学, 2021'],
    educationEn: ['BS, Biological Science, 2021'],
    researchInterests: ['岛屿生物地理学', '分子进化'],
    researchInterestsEn: ['Island Biogeography', 'Molecular Evolution'],
  },
  {
    id: '4',
    name: '蔡凯',
    nameEn: 'Kai Cai',
    role: 'Master Student',
    cohort: '2025级硕士',
    cohortEn: '2025 Master',
    image: './image/team/ck.jpg',
    description: '利用GIS技术分析自然保护区的有效性。',
    descriptionEn: 'Uses GIS technology to analyze the effectiveness of nature reserves.',
    fullBio: '蔡凯同学的研究兴趣在于探究全球孑遗物种与气候变化的响应关系，以及生物避难所的识别与保护。',
    fullBioEn: 'Kai Cai\'s research interests focus on exploring the response relationships between global relict species and climate change, as well as the identification and conservation of biological refugia.',
    education: ['学士, 地理信息系统, 陕西师范大学, 2025'],
    educationEn: ['BS, Geographic Information Systems, Shaanxi Normal University, 2025'],
    researchInterests: ['GIS应用', '统计分析', '遥感数据处理'],
    researchInterestsEn: ['GIS Applications', 'Statistical Analysis', 'Remote Sensing Data Processing'],
  }
];

export const PUBLICATIONS: Publication[] = [
  {
    id: 'p1',
    title: 'Global patterns of biodiversity conservation in the Anthropocene',
    titleEn: 'Global patterns of biodiversity conservation in the Anthropocene',
    authors: 'Zhang, X., Li, Y., et al.',
    journal: 'Nature Conservation',
    year: 2024,
    doi: '10.1038/s41559-024-0001-x',
    type: 'Journal',
  },
  {
    id: 'p2',
    title: 'Climate change impacts on alpine plant distributions in Southwest China',
    titleEn: 'Climate change impacts on alpine plant distributions in Southwest China',
    authors: 'Li, Y., Zhang, X.',
    journal: 'Journal of Biogeography',
    year: 2023,
    doi: '10.1111/jbi.12345',
    type: 'Journal',
  },
  {
    id: 'p3',
    title: 'Conservation Biogeography: Principles and Practices',
    titleEn: 'Conservation Biogeography: Principles and Practices',
    authors: 'Zhang, X. (Ed.)',
    journal: 'Academic Press',
    year: 2022,
    type: 'Book',
  }
];

export const RESEARCH_AREAS: ResearchArea[] = [
  {
    id: 'r1',
    title: '生物多样性格局',
    titleEn: 'Biodiversity Patterns',
    description: '研究物种在空间和时间上的分布规律及其驱动机制。',
    descriptionEn: 'Studying the spatial and temporal distribution patterns of species and their driving mechanisms.',
    icon: 'Globe',
  },
  {
    id: 'r2',
    title: '气候变化响应',
    titleEn: 'Climate Change Responses',
    description: '评估气候变化对生态系统和物种分布的影响及适应策略。',
    descriptionEn: 'Assessing the impacts of climate change on ecosystems and species distributions, and developing adaptation strategies.',
    icon: 'Thermometer',
  },
  {
    id: 'r3',
    title: '保护规划',
    titleEn: 'Conservation Planning',
    description: '利用空间分析技术制定科学的自然保护区规划和管理方案。',
    descriptionEn: 'Using spatial analysis techniques to develop scientific conservation area planning and management solutions.',
    icon: 'Map',
  }
];

export const NEWS_ITEMS: NewsItem[] = [
  {
    id: 'n1',
    title: '课题组在Nature Communications发表论文揭示全球保护区保护成效',
    titleEn: 'Group Publishes in Nature Communications on Global Protected Area Effectiveness',
    date: '2025-05-20',
    category: '论文发表',
    summary: '武瑞东老师团队在Nature Communications发表研究成果，系统评估了全球自然保护区在减缓生物多样性丧失方面的成效。',
    summaryEn: 'Prof. Wu\'s team published a study in Nature Communications systematically evaluating the effectiveness of global protected areas in mitigating biodiversity loss.',
    content: '2025年5月，课题组在Nature Communications上发表了题为"Global patterns of biodiversity conservation in the Anthropocene"的研究论文。该研究利用全球尺度的生物多样性数据，系统评估了过去30年间全球陆地自然保护区网络在减缓物种栖息地丧失和种群下降方面的成效。\n\n研究发现，虽然自然保护区的覆盖面积不断扩大，但保护成效存在显著的区域差异。热带地区的保护区面临更大的管理压力和人为干扰，亟需加强保护力度。\n\n该研究为全球生物多样性保护政策的制定提供了重要的科学依据，受到了国际学术界的广泛关注。',
    contentEn: 'In May 2025, the group published a research paper titled "Global patterns of biodiversity conservation in the Anthropocene" in Nature Communications. The study used global-scale biodiversity data to systematically evaluate the effectiveness of the global terrestrial protected area network in mitigating habitat loss and population declines over the past 30 years.\n\nThe study found that while protected area coverage has been continuously expanding, there are significant regional differences in conservation effectiveness. Protected areas in tropical regions face greater management pressures and human disturbances, requiring urgent strengthening of conservation efforts.\n\nThis research provides important scientific evidence for global biodiversity conservation policy-making and has received widespread attention from the international academic community.',
    image: 'https://picsum.photos/seed/nature-comms/800/400',
  },
  {
    id: 'n2',
    title: '课题组赴昆明参加第十五届全国生物多样性科学与保护研讨会',
    titleEn: 'Group Attends the 15th National Symposium on Biodiversity Science and Conservation',
    date: '2025-04-15',
    category: '学术会议',
    summary: '课题组成员参加了在昆明举办的第十五届全国生物多样性科学与保护研讨会，武瑞东老师作大会特邀报告，多名研究生进行海报展示。',
    summaryEn: 'Group members attended the 15th National Symposium on Biodiversity Science and Conservation in Kunming, where Prof. Wu gave an invited keynote and several graduate students presented posters.',
    content: '2025年4月12日至15日，第十五届全国生物多样性科学与保护研讨会在云南昆明举行。课题组全体成员参加了此次盛会。\n\n武瑞东老师应大会邀请作了题为"全球变化背景下的生物多样性保护优先区识别"的大会特邀报告，系统介绍了课题组近年来在保护优先区规划方面的最新研究成果，引起了与会学者的广泛关注和热烈讨论。\n\n博士研究生罗金怡和硕士研究生蔡凯分别以海报形式展示了各自的阶段性研究成果，其中罗金怡的海报获评"优秀海报奖"。\n\n会议期间，课题组还组织了与国内外多位专家的学术交流，为下一步的合作研究奠定了良好基础。',
    contentEn: 'From April 12 to 15, 2025, the 15th National Symposium on Biodiversity Science and Conservation was held in Kunming, Yunnan. All group members attended this grand event.\n\nProf. Wu was invited to give a keynote presentation titled "Identification of Biodiversity Conservation Priority Areas under Global Change," systematically introducing the group\'s latest research achievements in conservation priority area planning, which attracted widespread attention and lively discussion from attending scholars.\n\nPhD student Jinyi Luo and Master student Kai Cai presented their research progress as posters, with Jinyi Luo\'s poster winning the "Outstanding Poster Award."\n\nDuring the conference, the group also organized academic exchanges with multiple domestic and international experts, laying a good foundation for future collaborative research.',
    image: 'https://picsum.photos/seed/symposium2025/800/400',
  },
  {
    id: 'n3',
    title: '刘鑫博士获中国博士后科学基金面上资助',
    titleEn: 'Dr. Xin Liu Receives China Postdoctoral Science Foundation Grant',
    date: '2025-03-10',
    category: '获奖荣誉',
    summary: '课题组博士后刘鑫博士成功获得中国博士后科学基金面上资助，用于开展全球维管植物多样性热点区域的变化趋势研究。',
    summaryEn: 'Postdoc Dr. Xin Liu successfully obtained funding from the China Postdoctoral Science Foundation to study change trends in global vascular plant diversity hotspots.',
    content: '2025年3月，中国博士后科学基金会公布了第77批面上资助获选名单。课题组博士后刘鑫博士申报的项目"全球变化背景下维管植物多样性热点区域的时空变迁趋势"成功获得资助。\n\n该项目将利用全球尺度的植物分布数据，结合气候变化和土地利用变化情景，分析全球维管植物多样性热点区域的时空变迁趋势及其驱动机制，为全球植物多样性保护提供科学支撑。\n\n这是课题组博士后首次获得中国博士后科学基金资助，标志着课题组人才培养工作取得新进展。',
    contentEn: 'In March 2025, the China Postdoctoral Science Foundation announced the recipients of the 77th batch of general funding. Dr. Xin Liu\'s project "Spatiotemporal Change Trends of Vascular Plant Diversity Hotspots under Global Change" was successfully funded.\n\nThis project will use global-scale plant distribution data, combined with climate change and land use change scenarios, to analyze spatiotemporal change trends and driving mechanisms of global vascular plant diversity hotspots, providing scientific support for global plant diversity conservation.\n\nThis is the first time a postdoc in the group has received funding from the China Postdoctoral Science Foundation, marking new progress in the group\'s talent cultivation work.',
    image: 'https://picsum.photos/seed/grant2025/800/400',
  },
  {
    id: 'n4',
    title: '课题组启动云南省自然保护地整合优化研究项目',
    titleEn: 'Group Launches Yunnan Province Protected Area Integration and Optimization Research Project',
    date: '2025-01-05',
    category: '项目动态',
    summary: '课题组正式启动云南省自然保护地整合优化研究项目，旨在为云南省保护地体系建设提供科学决策支持。',
    summaryEn: 'The group officially launched a research project on the integration and optimization of protected areas in Yunnan Province, aiming to provide scientific decision support for the province\'s protected area system.',
    content: '2025年1月，课题组正式启动了"云南省自然保护地整合优化与生态产品价值核算"研究项目。该项目由云南省基础研究专项重大项目资助，执行期为三年。\n\n项目将围绕云南省"以国家公园为主体的自然保护地体系"建设需求，开展以下研究：\n1. 全省自然保护地空间分布格局与保护成效评估\n2. 保护地整合优化方案与优先区规划\n3. 重点区域生态产品价值核算\n\n项目启动会上，武瑞东老师明确了各成员的任务分工和工作计划，强调要注重科研成果的政策转化，为云南省生态文明建设贡献力量。',
    contentEn: 'In January 2025, the group officially launched the "Integration and Optimization of Protected Areas and Ecosystem Product Value Accounting in Yunnan Province" research project, funded by the Yunnan Provincial Basic Research Program Major Project with a three-year implementation period.\n\nThe project will focus on the needs of Yunnan Province\'s "protected area system with national parks as the main body" and conduct the following research:\n1. Assessment of spatial distribution patterns and conservation effectiveness of provincial protected areas\n2. Protected area integration and optimization plans and priority area planning\n3. Ecosystem product value accounting in key regions\n\nAt the project kick-off meeting, Prof. Wu clarified task assignments and work plans for each member, emphasizing the importance of translating research results into policy to contribute to Yunnan\'s ecological civilization construction.',
    image: 'https://picsum.photos/seed/project2025/800/400',
  },
  {
    id: 'n5',
    title: '课题组硕士研究生蔡凯通过学位论文开题答辩',
    titleEn: 'Master Student Kai Cai Passes Thesis Proposal Defense',
    date: '2024-12-18',
    category: '其他',
    summary: '蔡凯同学顺利通过硕士论文开题答辩，研究聚焦于全球孑遗物种对气候变化的脆弱性评估。',
    summaryEn: 'Kai Cai successfully passed his master thesis proposal defense, with research focusing on vulnerability assessment of global relict species to climate change.',
    content: '2024年12月18日，课题组二年级硕士研究生蔡凯同学顺利通过了学位论文开题答辩。\n\n蔡凯同学的论文题目为"全球孑遗物种分布格局及其对气候变化的脆弱性评估"，研究将整合全球孑遗物种的分布数据，利用物种分布模型和气候变化情景，评估不同气候情景下孑遗物种的灭绝风险和关键避难所分布。\n\n答辩委员会对选题的创新性和研究方案的可行性给予了充分肯定，并提出了建设性的修改建议。蔡凯同学将根据答辩委员会的意见进一步完善研究方案。',
    contentEn: 'On December 18, 2024, second-year Master student Kai Cai successfully passed his thesis proposal defense.\n\nKai\'s thesis is titled "Global Distribution Patterns of Relict Species and Their Vulnerability Assessment to Climate Change." The study will integrate global distribution data of relict species, using species distribution models and climate change scenarios to assess extinction risks and key refugia distribution under different climate scenarios.\n\nThe defense committee fully affirmed the innovation of the topic and the feasibility of the research plan, while providing constructive suggestions for improvement. Kai will further refine the research plan based on the committee\'s feedback.',
    image: 'https://picsum.photos/seed/defense2024/800/400',
  },
  {
    id: 'n6',
    title: '课题组研究成果被联合国生物多样性公约报告引用',
    titleEn: 'Group Research Cited in UN Convention on Biological Diversity Report',
    date: '2024-10-08',
    category: '获奖荣誉',
    summary: '课题组关于保护优先区规划的研究成果被联合国《生物多样性公约》全球生物多样性展望报告引用，彰显了课题组的国际学术影响力。',
    summaryEn: 'The group\'s research on conservation priority area planning was cited in the UN Convention on Biological Diversity\'s Global Biodiversity Outlook report, highlighting the group\'s international academic influence.',
    content: '2024年10月，联合国《生物多样性公约》（CBD）秘书处发布了第五版《全球生物多样性展望》（GBO-5），全面评估了全球生物多样性保护的进展与挑战。\n\n课题组此前在Nature Communications和Conservation Letters上发表的关于保护优先区识别和自然保护地规划的研究成果被该报告引用，作为支持全球生物多样性保护决策的科学依据。\n\n这一引用充分体现了课题组在保护生物地理学领域的国际学术影响力，也激励着课题组继续为全球生物多样性保护事业贡献中国智慧和中国方案。',
    contentEn: 'In October 2024, the Secretariat of the UN Convention on Biological Diversity (CBD) released the fifth edition of the Global Biodiversity Outlook (GBO-5), comprehensively assessing global progress and challenges in biodiversity conservation.\n\nThe group\'s previous research on conservation priority area identification and protected area planning, published in Nature Communications and Conservation Letters, was cited in this report as scientific evidence supporting global biodiversity conservation decision-making.\n\nThis citation fully reflects the group\'s international academic influence in the field of conservation biogeography and inspires the group to continue contributing Chinese wisdom and Chinese solutions to global biodiversity conservation.',
    image: 'https://picsum.photos/seed/cbd-report/800/400',
  },
];

export const LIFE_EVENTS: LifeEvent[] = [
  {
    id: 'l1',
    title: '2025年课题组新年聚餐',
    titleEn: '2025 New Year Group Dinner',
    date: '2025-01-15',
    category: '聚餐',
    description: '新年伊始，课题组全体成员齐聚一堂，在昆明市区的一家云南特色餐厅举行了新年聚餐。武瑞东老师总结了过去一年的科研成果，并对新一年的研究工作提出了期望。席间大家畅谈学术与生活，气氛热烈而温馨。',
    descriptionEn: 'To celebrate the New Year, all group members gathered at a Yunnan specialty restaurant in downtown Kunming for a festive dinner. Prof. Wu summarized the past year\'s research achievements and set expectations for the upcoming year. Everyone enjoyed lively discussions about both academic and personal life in a warm and joyful atmosphere.',
    coverImage: 'https://picsum.photos/seed/lab-dinner1/800/600',
    images: [
      'https://picsum.photos/seed/lab-dinner1/800/600',
      'https://picsum.photos/seed/lab-dinner2/800/600',
      'https://picsum.photos/seed/lab-dinner3/800/600',
    ],
  },
  {
    id: 'l2',
    title: '大理苍山野外考察',
    titleEn: 'Field Expedition to Cangshan Mountain, Dali',
    date: '2024-08-20',
    category: '野外考察',
    description: '课题组前往大理苍山进行了为期一周的野外考察，采集高山植物标本并记录植被分布数据。虽然山路崎岖，但大家互相帮助，圆满完成了考察任务。山间的清风与壮丽的景色让每一位成员都感受到了野外科研工作的独特魅力。',
    descriptionEn: 'The group conducted a week-long field expedition to Cangshan Mountain in Dali, collecting alpine plant specimens and recording vegetation distribution data. Despite the rugged terrain, everyone helped each other and successfully completed the mission. The mountain breeze and magnificent scenery reminded each member of the unique charm of field research.',
    coverImage: 'https://picsum.photos/seed/fieldwork1/800/600',
    images: [
      'https://picsum.photos/seed/fieldwork1/800/600',
      'https://picsum.photos/seed/fieldwork2/800/600',
      'https://picsum.photos/seed/fieldwork3/800/600',
      'https://picsum.photos/seed/fieldwork4/800/600',
    ],
  },
  {
    id: 'l3',
    title: '课题组春季团建——西山徒步',
    titleEn: 'Spring Team Building — Xishan Mountain Hike',
    date: '2024-04-10',
    category: '团建活动',
    description: '春光明媚的四月，课题组组织了一次西山徒步团建活动。从山脚到龙门，大家一边攀登一边交流，既锻炼了身体也增进了感情。登顶后俯瞰滇池全景，所有人都被眼前的美景所震撼。',
    descriptionEn: 'In the beautiful April spring, the group organized a hiking team-building activity at Xishan Mountain. From the foot to Longmen, everyone climbed while chatting, exercising both body and friendship. At the summit, the panoramic view of Dianchi Lake left everyone in awe.',
    coverImage: 'https://picsum.photos/seed/hiking1/800/600',
    images: [
      'https://picsum.photos/seed/hiking1/800/600',
      'https://picsum.photos/seed/hiking2/800/600',
      'https://picsum.photos/seed/hiking3/800/600',
    ],
  },
  {
    id: 'l4',
    title: '参加2024年国际生物地理学大会',
    titleEn: '2024 International Biogeography Conference',
    date: '2024-07-05',
    category: '学术会议',
    description: '课题组成员赴北京参加了2024年国际生物地理学大会。武瑞东老师做了题为"全球变化背景下的生物多样性保护优先区规划"的大会报告，多位研究生也以海报形式展示了自己的研究成果。会后大家还一起游览了长城和故宫。',
    descriptionEn: 'Group members traveled to Beijing for the 2024 International Biogeography Conference. Prof. Wu delivered a keynote presentation on "Conservation Priority Area Planning Under Global Change," and several graduate students presented their research as posters. After the conference, the group visited the Great Wall and the Forbidden City together.',
    coverImage: 'https://picsum.photos/seed/conference1/800/600',
    images: [
      'https://picsum.photos/seed/conference1/800/600',
      'https://picsum.photos/seed/conference2/800/600',
      'https://picsum.photos/seed/conference3/800/600',
      'https://picsum.photos/seed/conference4/800/600',
    ],
  },
  {
    id: 'l5',
    title: '中秋节月饼DIY活动',
    titleEn: 'Mid-Autumn Festival Mooncake DIY',
    date: '2024-09-17',
    category: '节日庆祝',
    description: '中秋佳节，课题组在实验室举办了一场别开生面的月饼DIY活动。大家亲手制作了各种口味的月饼，从和面到压模，每个人都乐在其中。虽然有些月饼形状不太完美，但满满的都是心意。活动结束后大家一边品尝劳动成果一边赏月，思乡之情在温暖的集体氛围中得到了慰藉。',
    descriptionEn: 'During the Mid-Autumn Festival, the group held a unique mooncake DIY event in the lab. Everyone made mooncakes of various flavors by hand — from kneading dough to pressing molds, each person enjoyed the process. Although some mooncakes weren\'t perfectly shaped, they were filled with heart. After the activity, everyone tasted their creations while admiring the moon, finding comfort in the warm group atmosphere.',
    coverImage: 'https://picsum.photos/seed/mooncake1/800/600',
    images: [
      'https://picsum.photos/seed/mooncake1/800/600',
      'https://picsum.photos/seed/mooncake2/800/600',
      'https://picsum.photos/seed/mooncake3/800/600',
    ],
  },
  {
    id: 'l6',
    title: '实验室日常——午间学术讨论',
    titleEn: 'Lab Daily Life — Lunchtime Academic Discussion',
    date: '2024-11-28',
    category: '日常',
    description: '每周四的午间学术讨论是课题组雷打不动的传统。大家围坐在一起，分享最新的文献阅读心得或者研究进展。轻松的氛围中，往往能碰撞出意想不到的灵感火花。这天轮到王同学分享他关于岛屿生物地理学的最新发现，引发了大家热烈的讨论。',
    descriptionEn: 'The Thursday lunchtime academic discussion is an unshakeable tradition of the group. Everyone gathers to share the latest literature insights or research progress. In the relaxed atmosphere, unexpected sparks of inspiration often emerge. On this day, it was Wang\'s turn to share his latest findings on island biogeography, sparking a lively discussion.',
    coverImage: 'https://picsum.photos/seed/seminar1/800/600',
    images: [
      'https://picsum.photos/seed/seminar1/800/600',
      'https://picsum.photos/seed/seminar2/800/600',
    ],
  },
];
